# Generated by Django 2.0 on 2017-12-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0005_remove_commissionform_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionform',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
