# Generated by Django 2.0 on 2017-12-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0006_commissionform_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionform',
            name='pub_date',
        ),
    ]
