# Generated by Django 2.0 on 2017-12-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0010_auto_20171211_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='areas',
            new_name='area',
        ),
    ]
