# Generated by Django 2.0 on 2017-12-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0004_auto_20171211_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionform',
            name='pub_date',
        ),
    ]
