# Generated by Django 2.0 on 2017-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0008_auto_20171211_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='commissionform',
            name='form_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionform',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='commissionform',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
